component: nuxtjs
name: nuxtjsDemo
org: orgDemo
app: appDemo
stage: dev

inputs:
  src:
    src: ./src
    exclude:
      - .env
      - node_modules
  region: ap-guangzhou
  runtime: Nodejs10.15
  apigatewayConf:
    protocols:
      - http
      - https
    environment: release
