component: nuxtjs
name: nuxtjsDemo
org: orgDemo
app: appDemo
stage: dev

inputs:
  src: ./src
  region: ap-guangzhou
  runtime: Nodejs10.15
  exclude:
    - .env
  apigatewayConf:
    protocols:
      - http
      - https
    environment: release
